# Generated by Django 5.1.2 on 2025-05-30 16:28

import autoslug.fields
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=users.models.generate_unique_slug, unique=True)),
                ('gradeLevel', models.CharField(choices=[('7', '7th grade'), ('8', '8th grade'), ('9', '9th grade'), ('10', '10th grade'), ('11', '11th grade'), ('12', '12th grade'), ('Postgraduate', 'Postgraduate')], default='12', max_length=15)),
                ('asking_price', models.DecimalField(decimal_places=2, default='10', max_digits=10)),
                ('teaching_language', models.CharField(choices=[('English', 'English'), ('German', 'German'), ('German and English', 'Both languages')], default='Eng', max_length=20)),
                ('picture', models.ImageField(default='fallback.png', upload_to='profile_pictures/')),
                ('body', models.TextField(max_length=1000)),
                ('verified', models.BooleanField(default=False)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='users.school')),
                ('subjects', models.ManyToManyField(to='users.subject')),
            ],
        ),
    ]
